#ifndef TEST_STUB_MAIN_H
#define TEST_STUB_MAIN_H

#include <stdint.h>

#define FRAME_WIDTH 800U
#define FRAME_HEIGHT 480U
#define FRAME_BUFFER_SIZE (FRAME_WIDTH * FRAME_HEIGHT * 2U)
#define SNAPSHOT_DECIMATION_FACTOR 2U
#define SNAPSHOT_WIDTH (FRAME_WIDTH / SNAPSHOT_DECIMATION_FACTOR)
#define SNAPSHOT_HEIGHT (FRAME_HEIGHT / SNAPSHOT_DECIMATION_FACTOR)
#define SNAPSHOT_FRAME_BUFFER_SIZE (SNAPSHOT_WIDTH * SNAPSHOT_HEIGHT * 2U)
#define BUFFER_ADDRESS 0x34200000U

void SCB_InvalidateDCache_by_Addr(uint32_t *addr, int32_t dsize);

#endif /* TEST_STUB_MAIN_H */
